In [8]:
from pathlib import Path
import pandas as pd

In [1]:
# ---------- Goal of this script ----------
# The goal of this script is to build weighted, directed graph

In [9]:
# ---------- Paths ----------

BASE_DIR = Path(".")
DATA_DIR = BASE_DIR / "Data"

DATA_FILE = DATA_DIR / "final_trip_data.parquet"

In [10]:
trip_data = pd.read_parquet(DATA_FILE)
trip_data.head()

,trip_id,start_date,start_station_id,start_station_name,end_date,end_station_id,end_station_name,bike_id,bike_model,total_duration,total_duration_ms,start_lat,start_lon,end_lat,end_lon
0,136666627,2024-01-14 23:59:00,1108,"North Wharf Road, Paddington",2024-01-15 00:06:00,3423.0,"Maida Vale, Maida Vale",53020.0,CLASSIC,6m 47s,407799.0,51.518623,-0.17660300000000007,51.529857,-0.18348604
1,136666625,2024-01-14 23:57:00,3447,"Gloucester Road (North), Kensington",2024-01-15 00:05:00,1214.0,"Kensington Olympia Station, Olympia",54559.0,CLASSIC,8m 1s,481276.0,51.49792478,-0.183834706,51.49815779,-0.209494128
2,136666626,2024-01-14 23:57:00,1090,"Warren Street Station, Euston",2024-01-15 00:02:00,200005.0,"New Cavendish Street, Marylebone",52133.0,CLASSIC,5m 11s,311788.0,51.52443845,-0.138019439,51.519167,-0.147983
3,136666622,2024-01-14 23:56:00,200058,"Northdown Street, King's Cross",2024-01-15 00:06:00,2687.0,"Brick Lane Market, Shoreditch",60341.0,PBSC_EBIKE,10m 14s,614030.0,51.531066,-0.11934,51.52261762,-0.071653961
4,136666623,2024-01-14 23:56:00,1052,"Soho Square , Soho",2024-01-15 00:23:00,1150.0,"Queensway, Kensington Gardens",55212.0,CLASSIC,27m 1s,1621583.0,51.51563144,-0.132328837,51.51031,-0.18740235

In [12]:
# ---------- Nodes dataframe ----------
# Każdy wierzchołek ma:
# - Numer stacji
# - Nazwa stacji 
# - Położenie geograficzne (dwie współrzędne)

start_stations_df = trip_data[
    [
        "start_station_id",
        "start_station_name",
        "start_lat",
        "start_lon",
    ]
].drop_duplicates()

start_stations_df = start_stations_df.rename(columns={
    "start_station_id": "station_id",
    "start_station_name": "station_name",
    "start_lat": "lat",
    "start_lon": "lon"
})

start_stations_df.head()

,station_id,station_name,lat,lon
0,1108,"North Wharf Road, Paddington",51.518623,-0.17660300000000007
1,3447,"Gloucester Road (North), Kensington",51.49792478,-0.183834706
2,1090,"Warren Street Station, Euston",51.52443845,-0.138019439
3,200058,"Northdown Street, King's Cross",51.531066,-0.11934
4,1052,"Soho Square , Soho",51.51563144,-0.132328837

In [13]:
end_stations_df = trip_data[
    [
        "end_station_id",
        "end_station_name",
        "end_lat",
        "end_lon",
    ]
].drop_duplicates()

end_stations_df = end_stations_df.rename(columns={
    "end_station_id": "station_id",
    "end_station_name": "station_name",
    "end_lat": "lat",
    "end_lon": "lon"
})

end_stations_df.head()

   station_id                         station_name          lat           lon
0      3423.0               Maida Vale, Maida Vale    51.529857   -0.18348604
1      1214.0  Kensington Olympia Station, Olympia  51.49815779  -0.209494128
2    200005.0     New Cavendish Street, Marylebone    51.519167     -0.147983
3      2687.0        Brick Lane Market, Shoreditch  51.52261762  -0.071653961
4      1150.0        Queensway, Kensington Gardens     51.51031   -0.18740235

In [16]:
stations_df = pd.concat([start_stations_df, end_stations_df], ignore_index=True).drop_duplicates()
print("Number of stations:", len(stations_df))

Number of stations: 801