In [ ]:
from pathlib import Path

import pandas as pd
import numpy as np

import networkx as nx

In [2]:
# ---------- Goal of this script ----------
# The goal of this script is to build weighted, directed graph

In [3]:
# ---------- Paths ----------

BASE_DIR = Path(".")
DATA_DIR = BASE_DIR / "Data"

DATA_FILE = DATA_DIR / "final_trip_data.parquet"

In [4]:
trip_data = pd.read_parquet(DATA_FILE)
trip_data.head()

,trip_id,start_date,start_station_id,start_station_name,end_date,end_station_id,end_station_name,bike_id,bike_model,total_duration,total_duration_ms,start_lat,start_lon,end_lat,end_lon
0,136666627,2024-01-14 23:59:00,1108,"North Wharf Road, Paddington",2024-01-15 00:06:00,3423.0,"Maida Vale, Maida Vale",53020.0,CLASSIC,6m 47s,407799.0,51.518623,-0.17660300000000007,51.529857,-0.18348604
1,136666625,2024-01-14 23:57:00,3447,"Gloucester Road (North), Kensington",2024-01-15 00:05:00,1214.0,"Kensington Olympia Station, Olympia",54559.0,CLASSIC,8m 1s,481276.0,51.49792478,-0.183834706,51.49815779,-0.209494128
2,136666626,2024-01-14 23:57:00,1090,"Warren Street Station, Euston",2024-01-15 00:02:00,200005.0,"New Cavendish Street, Marylebone",52133.0,CLASSIC,5m 11s,311788.0,51.52443845,-0.138019439,51.519167,-0.147983
3,136666622,2024-01-14 23:56:00,200058,"Northdown Street, King's Cross",2024-01-15 00:06:00,2687.0,"Brick Lane Market, Shoreditch",60341.0,PBSC_EBIKE,10m 14s,614030.0,51.531066,-0.11934,51.52261762,-0.071653961
4,136666623,2024-01-14 23:56:00,1052,"Soho Square , Soho",2024-01-15 00:23:00,1150.0,"Queensway, Kensington Gardens",55212.0,CLASSIC,27m 1s,1621583.0,51.51563144,-0.132328837,51.51031,-0.18740235

In [5]:
# ---------- Stations - nodes dataframe ----------
# Każdy wierzchołek ma:
# - Numer stacji
# - Nazwa stacji 
# - Położenie geograficzne (dwie współrzędne)

start_stations_df = trip_data[
    [
        "start_station_id",
        "start_station_name",
        "start_lat",
        "start_lon",
    ]
].drop_duplicates()

start_stations_df = start_stations_df.rename(columns={
    "start_station_id": "station_id",
    "start_station_name": "station_name",
    "start_lat": "lat",
    "start_lon": "lon"
})

start_stations_df.head()

,station_id,station_name,lat,lon
0,1108,"North Wharf Road, Paddington",51.518623,-0.17660300000000007
1,3447,"Gloucester Road (North), Kensington",51.49792478,-0.183834706
2,1090,"Warren Street Station, Euston",51.52443845,-0.138019439
3,200058,"Northdown Street, King's Cross",51.531066,-0.11934
4,1052,"Soho Square , Soho",51.51563144,-0.132328837

In [6]:
end_stations_df = trip_data[
    [
        "end_station_id",
        "end_station_name",
        "end_lat",
        "end_lon",
    ]
].drop_duplicates()

end_stations_df = end_stations_df.rename(columns={
    "end_station_id": "station_id",
    "end_station_name": "station_name",
    "end_lat": "lat",
    "end_lon": "lon"
})

end_stations_df.head()

   station_id                         station_name          lat           lon
0      3423.0               Maida Vale, Maida Vale    51.529857   -0.18348604
1      1214.0  Kensington Olympia Station, Olympia  51.49815779  -0.209494128
2    200005.0     New Cavendish Street, Marylebone    51.519167     -0.147983
3      2687.0        Brick Lane Market, Shoreditch  51.52261762  -0.071653961
4      1150.0        Queensway, Kensington Gardens     51.51031   -0.18740235

In [7]:
stations_df = pd.concat([start_stations_df, end_stations_df], ignore_index=True).drop_duplicates()
print("Number of stations:", len(stations_df))

Number of stations: 801

In [8]:
# Krawędzie A --> B mają wagę równą liczbie przejazdów z A do B
edges_df = trip_data.groupby(
    [
        "start_station_id",
        "start_station_name",
        "end_station_id",
        "end_station_name"
    ]
).agg(
    weight=("start_station_id", "count")
).reset_index()

In [9]:
edges_df.head(-10)

,start_station_id,start_station_name,end_station_id,end_station_name,weight
0,959,"Milroy Walk, South Bank",959.0,"Milroy Walk, South Bank",296
1,959,"Milroy Walk, South Bank",960.0,"Hop Exchange, The Borough",622
2,959,"Milroy Walk, South Bank",961.0,"Union Street, The Borough",159
3,959,"Milroy Walk, South Bank",962.0,"Stamford Street, South Bank",221
4,959,"Milroy Walk, South Bank",963.0,"Bankside Mix, Bankside",231
...,...,...,...,...,...
499733,300253,"Bermondsey Station, Bermondsey",300236.0,"Bevington Road West, North Kensington",1
499734,300253,"Bermondsey Station, Bermondsey",300237.0,"Tate Modern, Bankside",42
499735,300253,"Bermondsey Station, Bermondsey",300238.0,"Southwark Street, Bankside",8
499736,300253,"Bermondsey Station, Bermondsey",300239.0,"Victory Place, Walworth",22
499737,300253,"Bermondsey Station, Bermondsey",300240.0,"Lincoln's Inn Fields, Holborn",72

In [10]:
graph = nx.from_pandas_edgelist(
    edges_df,
    source="start_station_name",
    target="end_station_name",
    edge_attr="weight",
    create_using=nx.DiGraph()
)

positions = {}

stations_df["lat"] = stations_df["lat"].astype(float)
stations_df["lon"] = stations_df["lon"].astype(float)

for _, row in stations_df.iterrows():

    positions[row["station_name"]] = (
        row["lon"],
        row["lat"]
    )

In [11]:
graph.in_degree()

InDegreeView({'Milroy Walk, South Bank': 703, 'Hop Exchange, The Borough': 791, 'Union Street, The Borough': 693, 'Stamford Street, South Bank': 699, 'Bankside Mix, Bankside': 755, "Bath Street, St. Luke's": 729, 'Tachbrook Street, Victoria': 700, 'New Kent Road, The Borough': 685, 'Golden Lane, Barbican': 671, 'Warwick Row, Westminster': 771, 'Gower Place , Euston': 720, 'Scala Street, Fitzrovia': 682, "Godliman Street, St. Paul's": 757, 'Hampstead Road, Euston': 725, 'Bethnal Green Road, Shoreditch': 730, 'Guilford Street , Bloomsbury': 706, "Theobald's Road , Holborn": 716, "Longford Street, The Regent's Park": 599, 'Russell Square Station, Bloomsbury': 740, 'Wenlock Road , Hoxton': 608, 'Malet Street, Bloomsbury': 760, 'British Museum, Bloomsbury': 748, 'Holborn Circus, Holborn': 777, 'Euston Road, Euston': 687, 'Finsbury Circus, Liverpool Street': 768, 'Hatton Garden, Holborn': 714, 'Finsbury Library , Finsbury': 609, 'Great Russell Street, Bloomsbury': 749, 'Murray Grove , Hoxton': 598, 'Cotton Garden Estate, Kennington': 610, 'Crosswall, Tower': 775, 'St. John Street, Finsbury': 593, 'Drummond Street , Euston': 551, 'Tanner Street, Bermondsey': 704, 'Little Argyll Street, West End': 793, 'Borough High Street, The Borough': 701, 'Worship Street, Shoreditch': 713, 'Lollard Street, Vauxhall': 676, 'Queen Street 1, Bank': 784, 'Vauxhall Cross, Vauxhall': 741, 'Holy Trinity Brompton, Knightsbridge': 664, 'Chapel Place, Marylebone': 749, 'Doric Way , Somers Town': 665, 'Eversholt Street , Camden Town': 626, 'Percy Street, Bloomsbury': 732, 'Drury Lane, Covent Garden': 781, 'Hatton Wall, Holborn': 731, 'Taviton Street, Bloomsbury': 680, 'Cartwright Gardens , Bloomsbury': 675, 'Argyle Street, Kings Cross': 781, 'Christopher Street, Liverpool Street': 653, "St. Chad's Street, King's Cross": 690, 'New Globe Walk, Bankside': 678, 'Great Dover Street, The Borough': 669, 'Phillimore Gardens, Kensington': 656, 'Ampton Street , Clerkenwell': 593, 'Leonard Circus , Shoreditch': 695, 'Brunswick Square, Bloomsbury': 694, 'River Street , Clerkenwell': 610, 'Park Street, Bankside': 706, 'Bolsover Street, Fitzrovia': 713, "Roscoe Street, St. Luke's": 622, 'Warwick Avenue Station, Maida Vale': 663, 'William IV Street, Strand': 786, 'Windsor Terrace, Hoxton': 649, "Lisson Grove, St. John's Wood": 509, 'Nesham Street, Wapping': 671, 'New Inn Yard, Shoreditch': 670, 'Paddington Street, Marylebone': 704, 'Bruton Street, Mayfair': 706, 'Boston Place, Marylebone': 705, 'Crawford Street, Marylebone': 696, 'Park Lane , Hyde Park': 737, 'Harrington Square 1, Camden Town': 663, 'Wapping High Street, Wapping': 537, 'West Smithfield Rotunda, Farringdon': 735, 'Westbourne Grove, Bayswater': 636, 'Woodstock Street, Mayfair': 738, 'Museum of London, Barbican': 699, 'The Guildhall, Guildhall': 695, 'Jewry Street, Aldgate': 705, 'Vauxhall Bridge , Pimlico': 669, 'Falkirk Street, Hoxton': 573, "Queen Victoria Street, St. Paul's": 759, "Finsbury Leisure Centre, St. Luke's": 681, "Park Road (Baker Street), The Regent's Park": 699, 'Shoreditch Park, Hoxton': 654, 'Soho Square , Soho': 794, 'Clerkenwell Green, Clerkenwell': 709, 'East Road, Hoxton': 590, "Wellington Road, St. John's Wood": 627, 'Finsbury Square , Moorgate': 712, 'Hardwick Street, Clerkenwell': 569, 'Albert Embankment, Vauxhall': 673, 'Torrens Street, Angel': 612, 'Stonecutter Street, Holborn': 595, 'Braham Street, Aldgate': 728, 'Wood Street, Guildhall': 670, "Old Street Station, St. Luke's": 761, 'Aldersgate Street, Barbican': 731, "Calshot Street , King's Cross": 579, "St. James's Square, St. James's": 791, 'Norton Folgate, Liverpool Street': 696, 'Eaton Square, Belgravia': 495, 'Bricklayers Arms, Borough': 693, 'Tower Gardens , Tower': 768, 'Waterloo Station 3, Waterloo': 691, 'Kennington Road Post Office, Oval': 672, "Newgate Street , St. Paul's": 762, 'Hyde Park Corner, Hyde Park': 783, 'Walnut Tree Walk, Vauxhall': 614, 'Royal London Hospital, Whitechapel': 669, 'Lambeth Road, Vauxhall': 650, 'Endsleigh Gardens, Euston': 726, 'Great Tower Street, Monument': 770, 'Liverpool Road (N1 Centre), Angel': 712, 'Borough Road, Elephant & Castle': 716, 'Commercial Street, Shoreditch': 613, 'Pindar Street, Liverpool Street': 583, 'Old Quebec Street, Marylebone': 729, 'Baker Street, Marylebone': 684, 'Belgrave Road, Victoria': 713, 'Triangle Car Park, Hyde Park': 688, "Queen's Gate (Central), South Kensington": 631, 'Warren Street Station, Euston': 756, 'Moorfields, Moorgate': 764, 'Kennington Cross, Kennington': 717, "Wright's Lane, Kensington": 695, 'LSBU (Borough Road), Elephant & Castle': 673, 'Bayswater Road, Hyde Park': 734, 'Northumberland Avenue, Strand': 769, 'Lower Thames Street, Monument': 698, 'Frampton Street, Paddington': 591, 'Strand, Strand': 785, 'Knightsbridge, Hyde Park': 563, 'Leman Street, Aldgate': 693, 'Gloucester Street, Pimlico': 702, 'Claremont Square, Angel': 648, 'LMU Commercial Road, Whitechapel': 617, 'Rampayne Street, Pimlico': 699, 'Gloucester Road Station, South Kensington': 680, 'North Wharf Road, Paddington': 653, 'Wellington Arch, Hyde Park': 787, 'Palace Gate, Kensington Gardens': 635, 'Nutford Place, Marylebone': 629, "Trebovir Road, Earl's Court": 612, 'Pont Street, Knightsbridge': 671, "Emperor's Gate, South Kensington": 626, 'Lambeth North Station, Waterloo': 688, 'Hampton Street, Walworth': 705, 'Chepstow Villas, Notting Hill': 632, 'Lexham Gardens, Kensington': 600, 'Ashley Place, Victoria': 733, 'Southampton Place, Holborn': 743, 'Sumner Place, South Kensington': 620, 'North Audley Street, Mayfair': 745, 'Risinghill Street, Angel': 632, 'Westbourne Green, Westbourne': 598, 'Sun Street, Liverpool Street': 710, 'Graham Street, Angel': 671, 'Albert Gate, Hyde Park': 752, 'Baylis Road, Waterloo': 754, 'Warwick Road, Olympia': 657, 'Claverton Street, Pimlico': 697, "London Zoo,  The Regent's Park": 575, 'Harper Road, The Borough': 683, 'Elizabeth Bridge, Victoria': 766, 'Carey Street, Holborn': 697, 'Grosvenor Road, Pimlico': 613, 'Kingsway, Covent Garden': 675, 'Tooley Street, Bermondsey': 776, 'Kensington Church Street, Kensington': 647, 'Poured Lines, Bankside': 705, 'Bucknall Street, Covent Garden': 747, 'Tysoe Street, Clerkenwell': 740, 'Clifton Road, Maida Vale': 599, 'Queen Mother Sports Centre, Victoria': 715, 'Queensway, Kensington Gardens': 707, 'Whitehall Place, Strand': 792, 'Marylebone Lane, Marylebone': 756, 'Pall Mall East, West End': 774, 'Kennington Road, Vauxhall': 690, 'Regency Street, Westminster': 693, 'Bedford Way, Bloomsbury': 688, 'Black Lion Gate, Kensington Gardens': 720, "St. Martin's Street, West End": 765, 'Berry Street, Clerkenwell': 708, 'Craven Street, Strand': 793, 'Brushfield Street, Liverpool Street': 776, 'Dorset Square, Marylebone': 719, 'Wardour Street, Soho': 781, 'Portland Place, Marylebone': 708, 'Riverlight North, Nine Elms': 709, 'Bell Street , Marylebone': 633, 'South Wharf Road, Paddington': 691, 'Grosvenor Crescent, Belgravia': 607, 'Horseferry Road, Westminster': 730, 'New Road 1 , Whitechapel': 633, "Queen's Gate (South), South Kensington": 638, 'Gloucester Terrace, Bayswater': 590, 'Alderney Street, Pimlico': 703, 'Mallory Street, Marylebone': 488, 'Waterloo Road, South Bank': 663, 'Seville Street, Knightsbridge': 733, 'Bourne Street, Belgravia': 669, 'Notting Hill Gate Station, Notting Hill': 702, 'St. Mary Axe, Aldgate': 726, 'Belvedere Road 1, South Bank': 753, "London Zoo Car Park, The Regent's Park": 600, 'Long Lane , Bermondsey': 663, 'Kennington Lane Rail Bridge, Vauxhall': 736, 'Barbican Centre, Barbican': 705, 'Embankment (Savoy), Strand': 768, 'Kensington Gore, Knightsbridge': 691, 'Westminster University, Marylebone': 679, "St. George's Square, Pimlico": 697, 'Vincent Square, Westminster': 650, 'Sackville Street, Mayfair': 757, "The Tennis Courts, The Regent's Park": 586, 'Ontario Street, Elephant & Castle': 699, 'Bank of England Museum, Bank': 746, 'Wellington Street , Strand': 783, 'Eastbourne Mews, Paddington': 710, "Queen's Gate (North), Kensington": 642, 'Black Prince Road, Vauxhall': 663, 'Montpelier Street, Knightsbridge': 709, 'Tavistock Street, Covent Garden': 778, 'Dickens Square, Borough': 626, 'Empire Square, The Borough': 671, "Nevern Place, Earl's Court": 549, 'Bunhill Row, Moorgate': 727, 'Concert Hall Approach, South Bank': 511, 'Curlew Street, Shad Thames': 691, 'Kensington Olympia Station, Olympia': 531, 'Swan Street, The Borough': 675, 'Serpentine Car Park, Hyde Park': 728, 'Flood Street, Chelsea': 696, 'Lower Marsh, Waterloo': 712, 'Imperial College, Knightsbridge': 665, 'St. George Street, Mayfair': 749, 'Goswell Road (City Uni), Finsbury': 574, 'Vauxhall Street, Vauxhall': 684, 'George Street, Marylebone': 712, 'Macclesfield Rd, St Lukes': 649, 'Devonshire Terrace, Bayswater': 671, 'Southampton Street, Strand': 777, 'High Holborn , Covent Garden': 755, 'Millennium Hotel, Mayfair': 664, "Queen's Gate, Kensington Gardens": 726, 'Cloudesley Road, Angel': 618, 'Wormwood Street, Liverpool Street': 784, 'Pembridge Villas, Notting Hill': 623, 'Palace Gardens Terrace, Notting Hill': 694, "Prince Albert Road, The Regent's Park": 650, 'Bermondsey Street, Bermondsey': 684, 'King Edward Walk, Waterloo': 515, 'Waterloo Bridge, South Bank': 673, 'Sardinia Street, Holborn': 689, 'Frith Street, Soho': 781, 'Butler Place, Westminster': 715, "Lord's, St. John's Wood": 497, 'Howick Place, Westminster': 745, 'Tower Wharf, Bermondsey': 690, 'Charlotte Street, Fitzrovia': 719, 'Paddington Green, Paddington': 490, 'Natural History Museum, South Kensington': 624, 'Farm Street, Mayfair': 653, 'George Row, Bermondsey': 653, 'Harrowby Street, Marylebone': 639, 'Turquoise Island, Notting Hill': 628, 'Millbank Tower, Pimlico': 759, 'South Kensington Station, South Kensington': 719, 'Royal College Street, Camden Town': 575, 'Brick Lane Market, Shoreditch': 639, 'Clifford Street, Mayfair': 723, 'City Road, Angel': 604, 'Howland Street, Fitzrovia': 740, 'Waterloo Station 2, Waterloo': 716, 'Clapham Common Station, Clapham Common': 751, 'Cadogan Gardens, Chelsea': 691, 'Waterloo Station 1, Waterloo': 790, "Aberdeen Place, St. John's Wood": 510, 'Snow Hill, Farringdon': 673, 'Columbia Road, Shoreditch': 674, 'Fire Brigade Pier, Vauxhall': 669, 'Sedding Street, Sloane Square': 722, 'Red Lion Square, Holborn': 688, 'Maida Vale, Maida Vale': 704, 'Broadcasting House, Marylebone': 755, 'Northington Street , Holborn': 698, 'Lansdowne Drive, Hackney Central': 607, 'Fanshaw Street, Hoxton': 657, "Pancras Road, King's Cross": 601, 'Abbey Orchard Street, Westminster': 756, 'Central House, Aldgate': 663, 'Grafton Street, Mayfair': 715, 'Farringdon Lane, Clerkenwell': 692, 'Sadlers Sports Centre, Finsbury': 667, 'Sancroft Street, Vauxhall': 588, 'Gloucester Road (Central), South Kensington': 591, 'Derry Street, Kensington': 725, 'Curzon Street, Mayfair': 701, 'Tavistock Place, Bloomsbury': 675, 'Royal Avenue 1, Chelsea': 636, 'Vicarage Gate, Kensington': 573, "Penywern Road, Earl's Court": 630, 'Shoreditch High Street, Shoreditch': 721, 'Gloucester Road (North), Kensington': 637, 'Webber Street , Southwark': 679, 'Breams Buildings, Holborn': 730, 'Great Titchfield Street, Fitzrovia': 693, 'Golden Square, Soho': 777, 'Panton Street, West End': 782, 'Arundel Street, Temple': 735, 'Portugal Street, Holborn': 614, 'Rochester Row, Westminster': 700, "Waterloo Place, St. James's": 760, 'Warwick Square, Pimlico': 673, 'Sloane Avenue, Knightsbridge': 662, 'Royal Avenue 2, Chelsea': 661, 'Argyll Road, Kensington': 576, 'Green Street, Mayfair': 725, 'Eccleston Place, Victoria': 765, 'Dock Street, Wapping': 697, 'Margery Street, Clerkenwell': 606, 'Cadogan Place, Knightsbridge': 665, 'Great Percy Street, Clerkenwell': 601, 'Chadwell Street, Angel': 599, 'Colombo Street, Southwark': 500, 'Belgrave Square, Belgravia': 646, 'Hinde Street, Marylebone': 756, 'Porchester Place, Paddington': 720, 'Guildhouse Street, Victoria': 686, 'Old Brompton Road, South Kensington': 631, 'Smith Square, Westminster': 743, 'Rodney Road , Walworth': 652, 'Beaumont Street, Marylebone': 704, 'Fashion Street, Whitechapel': 620, 'Houghton Street, Strand': 732, 'Tyers Gate, Bermondsey': 674, 'Charles II Street, West End': 764, 'Broadwick Street, Soho': 780, 'Southwick Street, Paddington': 652, 'Princes Square, Bayswater': 543, 'South Audley Street, Mayfair': 622, 'Foley Street, Fitzrovia': 724, 'Wells Street, Fitzrovia': 758, "St Mary's Hospital, Paddington": 721, 'Rathbone Street, Fitzrovia': 713, 'Geraldine Street, Elephant & Castle': 550, "Baldwin Street, St. Luke's": 668, 'Clifton Street, Shoreditch': 582, 'Palissy Street, Shoreditch': 586, 'Moor Street, Soho': 784, 'Stanhope Gate, Mayfair': 638, 'Store Street, Bloomsbury': 746, 'Greycoat Street , Westminster': 616, 'Strata, Elephant & Castle': 762, 'Grosvenor Square, Mayfair': 715, 'Cleaver Street, Kennington': 589, 'Rotherhithe Roundabout, Rotherhithe': 629, 'George Place Mews, Marylebone': 657, 'Holland Park, Kensington': 508, 'Kensington Town Hall, Kensington': 516, 'Exhibition Road Museums 1, South Kensington': 731, 'Ebury Bridge, Pimlico': 679, 'Chelsea Bridge, Pimlico': 683, 'Vincent Street, Pimlico': 658, 'Southwark Station 2, Southwark': 741, 'Eaton Square (South), Belgravia': 661, "Fisherman's Walk West, Canary Wharf": 595, 'Albert Gardens, Stepney': 575, 'Wren Street, Holborn': 675, 'Kennington Station, Kennington': 665, 'Red Lion Street, Holborn': 746, 'Bromley High Street, Bow': 486, 'Old Ford Road, Bethnal Green': 454, 'Granby Street, Shoreditch': 637, 'Canton Street, Poplar': 455, 'Reardon Street, Wapping': 565, 'Christian Street, Whitechapel': 601, 'Lindfield Street, Poplar': 508, 'Exhibition Road, Knightsbridge': 766, 'Cheapside, Bank': 774, 'Camley Street, Camden Town': 486, 'South Parade, Chelsea': 618, "Crinan Street, King's Cross": 620, 'Limerston Street, West Chelsea': 704, 'Jubilee Street, Stepney': 528, 'Cheshire Street, Bethnal Green': 499, 'Lightermans Road, Millwall': 547, 'New Cavendish Street, Marylebone': 725, 'Hewison Street, Old Ford': 463, 'Holden Street, Battersea': 497, 'Portman Square, Marylebone': 701, 'Manresa Road, Chelsea': 640, 'Furze Green, Bow': 501, 'Stepney Green Station, Stepney': 609, 'Aston Street, Stepney': 493, 'Gunmakers Lane, Old Ford': 480, 'Castlehaven Road, Camden Town': 737, 'Lancaster Gate , Bayswater': 616, 'Spindrift Avenue, Millwall': 400, 'Malmesbury Road, Bow': 305, 'Shadwell Station, Shadwell': 678, 'Hermitage Court, Wapping': 592, 'Saunders Ness Road, Cubitt Town': 565, 'Queensbridge Road, Haggerston': 546, 'London Fields, Hackney Central': 677, 'Greenland Road, Camden Town': 742, 'Ford Road, Old Ford': 481, 'Finlay Street, Fulham': 558, 'Driffield Road, Old Ford': 514, 'East Ferry Road, Cubitt Town': 394, 'Kennington Oval, Oval': 696, 'Philpot Street, Whitechapel': 583, 'Wapping Lane, Wapping': 606, 'Bell Lane, Liverpool Street': 680, 'Ackroyd Drive, Bow': 490, 'Sail Street, Vauxhall': 656, 'Antill Road, Mile End': 507, 'York Hall, Bethnal Green': 530, "Bishop's Avenue, Fulham": 515, 'New Fetter Lane, Holborn': 719, 'Bethnal Green Garden, Bethnal Green': 517, 'Page Street, Westminster': 717, "St. Katharine's Way, Tower": 622, 'Percival Street, Finsbury': 573, 'Exhibition Road Museums 2, South Kensington': 688, "Killick Street, King's Cross": 511, 'Vauxhall Walk, Vauxhall': 626, 'Belford House, Haggerston': 462, "Northdown Street, King's Cross": 631, 'Crisp Road, Hammersmith': 609, 'Drayton Gardens, West Chelsea': 673, 'William Morris Way, Sands End': 593, "Regent's Row , Haggerston": 665, 'Import Dock, Canary Wharf': 578, 'Somerset House, Strand': 768, "Knaresborough Place, Earl's Court": 599, 'Arlington Road, Camden Town': 602, 'Hoxton Street, Hoxton': 559, 'Houndsditch, Aldgate': 720, 'Cephas Street, Bethnal Green': 524, 'Bury Place, Holborn': 719, 'Westminster Bridge Road, Elephant & Castle': 534, 'Vicarage Crescent, Battersea': 626, 'Aberfeldy Street, Poplar': 363, 'Ram Street, Wandsworth': 632, 'Russell Gardens, Olympia': 468, 'Coomer Place, West Kensington': 598, 'St. Mary & St. Michael Church, Stepney': 432, "Pritchard's Road, Bethnal Green": 586, 'Doddington Grove, Kennington': 673, 'Ilchester Gardens, Bayswater': 602, 'Pennington Street, Wapping': 514, 'Wandsworth Town Station, Wandsworth': 583, 'Thurtle Road, Haggerston': 467, 'St. Bride Street, Holborn': 755, 'Green Park Station, Mayfair': 771, 'Aintree Street, Fulham': 552, 'Upper Bank Street, Canary Wharf': 593, 'Monument Street, Monument': 767, 'Harford Street, Mile End': 403, 'Bonny Street, Camden Town': 707, "Bishop's Bridge Road East, Bayswater": 579, 'Alpha Grove, Millwall': 442, "Bishop's Bridge Road West, Bayswater": 661, 'Cadogan Close, Victoria Park': 483, 'Smugglers Way, Wandsworth': 567, 'Orbel Street, Battersea': 573, 'Flamborough Street, Limehouse': 659, 'Vereker Road, West Kensington': 588, 'Albert Street, Camden Town': 556, 'Dorothy Road, Clapham Junction': 632, 'Grant Road East, Clapham Junction': 521, 'Hawley Crescent, Camden Town': 610, 'Burdett Road, Mile End': 483, 'Putney Bridge Station, Fulham': 533, 'Usk Road, Clapham Junction': 596, 'East India DLR, Blackwall': 499, 'Queen Street 2, Bank': 792, 'Charlotte Terrace, Angel': 606, 'Clarkson Street, Bethnal Green': 497, 'Gaywood  Street, Elephant & Castle': 670, 'South Lambeth Road, Vauxhall': 714, "Albany Street, The Regent's Park": 618, 'Selby Street, Whitechapel': 470, 'Caldwell Street, Stockwell': 694, 'Westfield Ariel Way, White City': 577, 'Hammersmith Road, Hammersmith': 665, 'Sea Containers, South Bank': 723, 'Gloucester Avenue, Camden Town': 614, 'Newby Place, Poplar': 454, 'Salmon Lane, Limehouse': 561, 'Ansell House, Stepney': 553, 'Watney Street, Shadwell': 571, 'Hoxton Station, Hoxton': 609, 'Pitfield Street North,Hoxton': 624, 'Gascoyne Road, Victoria Park': 542, 'Pott Street, Bethnal Green': 583, 'Fournier Street, Whitechapel': 705, 'Whiston Road, Haggerston': 540, "Goldsmith's Row, Haggerston": 634, 'Langdon Park, Poplar': 388, 'Clinton Road, Mile End': 532, 'Watney Market, Stepney': 494, 'Jubilee Plaza, Canary Wharf': 673, 'Wellington Row, Bethnal Green': 605, 'Southerton Road, Hammersmith': 628, 'Twig Folly Bridge, Mile End': 538, 'Ashley Crescent, Battersea': 653, 'Courland Grove, Wandsworth Road': 589, 'Mostyn Grove, Bow': 482, 'Wandsworth Rd, Isley Court, Wandsworth Road': 620, 'Sheepcote Lane, Battersea': 566, 'Buckingham Gate, Westminster': 753, 'Silverthorne Road, Battersea': 624, 'South Park, Sands End': 471, 'Battersea Park Road, Nine Elms': 759, "St. John's Road, Clapham Junction": 646, 'Morie Street, Wandsworth': 484, 'Neville Gill Close, Wandsworth': 594, 'Phene Street, Chelsea': 663, "Queen's Circus, Battersea Park": 690, 'Spencer Park, Wandsworth Common': 515, 'Fawcett Close, Battersea': 492, 'Snowsfields, London Bridge': 737, 'Clarence Walk, Stockwell': 563, 'St Martins Close, Camden Town': 562, 'Simpson Street, Clapham Junction': 678, 'Seymour Place, Marylebone': 696, 'Stanley Grove, Battersea': 535, 'Great Suffolk Street, The Borough': 639, 'Battersea Church Road, Battersea': 656, "Storey's Gate, Westminster": 790, 'King Edward Street, St Pauls': 649, 'Chicheley Street, South Bank': 782, 'Hartington Road, Stockwell': 667, 'Sugden Road, Clapham': 657, "Shepherd's Bush Road North, Shepherd's Bush": 578, 'Westbridge Road, Battersea': 699, 'Union Grove, Wandsworth Road': 659, "Blackfriars Station, St. Paul's": 766, 'Durant Street, Bethnal Green': 565, "Woodstock Grove, Shepherd's Bush": 628, 'Greyhound Road, Hammersmith': 565, 'Clements Road, Bermondsey': 539, 'Disraeli Road, Putney': 529, 'Osiers Road, Wandsworth': 543, 'Danvers Street, West Chelsea': 654, 'Ashmole Estate, Oval': 654, 'Kingsway Southbound, Strand': 750, "Westfield Library Corner, Shepherd's Bush": 615, 'Fulham Park Road, Fulham': 569, 'Maplin Street, Mile End': 507, 'Abingdon Green, Westminster': 754, 'South Quay East, Canary Wharf': 338, 'Bancroft Road, Bethnal Green': 479, 'Manbre Road, Hammersmith': 442

In [12]:
nx.is_weakly_connected(graph)

True

In [13]:
nx.is_strongly_connected(graph)

True

In [14]:
np.mean([degree for _, degree in graph.degree()])

np.float64(1247.8102372034957)

In [15]:
nx.pagerank(graph, weight="weight")

{'Milroy Walk, South Bank': 0.0011678072314575587,
 'Hop Exchange, The Borough': 0.004480859839425038,
 'Union Street, The Borough': 0.001170377910722598,
 'Stamford Street, South Bank': 0.0012799473407231865,
 'Bankside Mix, Bankside': 0.0015595731867833339,
 "Bath Street, St. Luke's": 0.0016270011093740661,
 'Tachbrook Street, Victoria': 0.0013035342191816555,
 'New Kent Road, The Borough': 0.0012039462213224205,
 'Golden Lane, Barbican': 0.0011454908803765968,
 'Warwick Row, Westminster': 0.002232261148623905,
 'Gower Place , Euston': 0.0012078433364366534,
 'Scala Street, Fitzrovia': 0.001037743132402183,
 "Godliman Street, St. Paul's": 0.0015192221259802809,
 'Hampstead Road, Euston': 0.0017204003087401476,
 'Bethnal Green Road, Shoreditch': 0.0025663031695116654,
 'Guilford Street , Bloomsbury': 0.001689110218386588,
 "Theobald's Road , Holborn": 0.0012979473792098936,
 "Longford Street, The Regent's Park": 0.000819532280368342,
 'Russell Square Station, Bloomsbury': 0.0015129534749320722,
 'Wenlock Road , Hoxton': 0.00124206583731706,
 'Malet Street, Bloomsbury': 0.0022582793216033353,
 'British Museum, Bloomsbury': 0.0016131755888791099,
 'Holborn Circus, Holborn': 0.002888853689438672,
 'Euston Road, Euston': 0.0008295622291136797,
 'Finsbury Circus, Liverpool Street': 0.0028099223065282813,
 'Hatton Garden, Holborn': 0.001448977380151188,
 'Finsbury Library , Finsbury': 0.0007997592902925681,
 'Great Russell Street, Bloomsbury': 0.0013428256116167674,
 'Murray Grove , Hoxton': 0.0009650460975392972,
 'Cotton Garden Estate, Kennington': 0.0008400309269857946,
 'Crosswall, Tower': 0.0026575648363915422,
 'St. John Street, Finsbury': 0.0007400279799935298,
 'Drummond Street , Euston': 0.0007686070167345299,
 'Tanner Street, Bermondsey': 0.0015314478404276227,
 'Little Argyll Street, West End': 0.0029400880583218903,
 'Borough High Street, The Borough': 0.0012203889363229953,
 'Worship Street, Shoreditch': 0.0016066428665390902,
 'Lollard Street, Vauxhall': 0.0013099622759414802,
 'Queen Street 1, Bank': 0.00335374336367658,
 'Vauxhall Cross, Vauxhall': 0.002206186827423661,
 'Holy Trinity Brompton, Knightsbridge': 0.0012996068794099349,
 'Chapel Place, Marylebone': 0.001354562153496452,
 'Doric Way , Somers Town': 0.0013597008272795998,
 'Eversholt Street , Camden Town': 0.0009112350215402917,
 'Percy Street, Bloomsbury': 0.0009525263076772574,
 'Drury Lane, Covent Garden': 0.00223001229670615,
 'Hatton Wall, Holborn': 0.0016767620893016581,
 'Taviton Street, Bloomsbury': 0.0014324546624770612,
 'Cartwright Gardens , Bloomsbury': 0.0011593974263969067,
 'Argyle Street, Kings Cross': 0.0036510426578663917,
 'Christopher Street, Liverpool Street': 0.0009726734209711105,
 "St. Chad's Street, King's Cross": 0.0008642236531079726,
 'New Globe Walk, Bankside': 0.0009695784774338355,
 'Great Dover Street, The Borough': 0.0014933388669157012,
 'Phillimore Gardens, Kensington': 0.0015768707818340638,
 'Ampton Street , Clerkenwell': 0.0009226114621536492,
 'Leonard Circus , Shoreditch': 0.0014462978926268238,
 'Brunswick Square, Bloomsbury': 0.0015484751612006551,
 'River Street , Clerkenwell': 0.0006768326249856457,
 'Park Street, Bankside': 0.0009158866941220527,
 'Bolsover Street, Fitzrovia': 0.0012844580760669971,
 "Roscoe Street, St. Luke's": 0.000931253311627469,
 'Warwick Avenue Station, Maida Vale': 0.0012650178091247169,
 'William IV Street, Strand': 0.0021970849688891436,
 'Windsor Terrace, Hoxton': 0.0011212289720168214,
 "Lisson Grove, St. John's Wood": 0.0006387073640139527,
 'Nesham Street, Wapping': 0.002015464689640333,
 'New Inn Yard, Shoreditch': 0.0014251006350524138,
 'Paddington Street, Marylebone': 0.0013556710831515092,
 'Bruton Street, Mayfair': 0.0008425851087534573,
 'Boston Place, Marylebone': 0.0016290853253000802,
 'Crawford Street, Marylebone': 0.0014552978755513462,
 'Park Lane , Hyde Park': 0.0020322630988779864,
 'Harrington Square 1, Camden Town': 0.0010523751247002203,
 'Wapping High Street, Wapping': 0.0007738062431701326,
 'West Smithfield Rotunda, Farringdon': 0.0016302644736209725,
 'Westbourne Grove, Bayswater': 0.0010778152851426558,
 'Woodstock Street, Mayfair': 0.0008863377373077481,
 'Museum of London, Barbican': 0.001587419003443049,
 'The Guildhall, Guildhall': 0.0009861383427553763,
 'Jewry Street, Aldgate': 0.0011248704967644991,
 'Vauxhall Bridge , Pimlico': 0.0007435514424577534,
 'Falkirk Street, Hoxton': 0.0009721433207065312,
 "Queen Victoria Street, St. Paul's": 0.001433851554975709,
 "Finsbury Leisure Centre, St. Luke's": 0.001742165861851073,
 "Park Road (Baker Street), The Regent's Park": 0.0017536815288911483,
 'Shoreditch Park, Hoxton': 0.0013092312520203231,
 'Soho Square , Soho': 0.0036722881805570516,
 'Clerkenwell Green, Clerkenwell': 0.0015266311638707142,
 'East Road, Hoxton': 0.0009076930366981257,
 "Wellington Road, St. John's Wood": 0.0009592222725965265,
 'Finsbury Square , Moorgate': 0.001356049411919133,
 'Hardwick Street, Clerkenwell': 0.0006442095719585943,
 'Albert Embankment, Vauxhall': 0.0008638489272322625,
 'Torrens Street, Angel': 0.0006455524080076638,
 'Stonecutter Street, Holborn': 0.0005014398402604126,
 'Braham Street, Aldgate': 0.0021644973021758868,
 'Wood Street, Guildhall': 0.0009242339019805664,
 "Old Street Station, St. Luke's": 0.002929342584682832,
 'Aldersgate Street, Barbican': 0.0019729822773157453,
 "Calshot Street , King's Cross": 0.0006043954285006269,
 "St. James's Square, St. James's": 0.003963744241897108,
 'Norton Folgate, Liverpool Street': 0.0012352175802677042,
 'Eaton Square, Belgravia': 0.00036669636281532825,
 'Bricklayers Arms, Borough': 0.0015897237771110634,
 'Tower Gardens , Tower': 0.0022742457245424302,
 'Waterloo Station 3, Waterloo': 0.005279264909676868,
 'Kennington Road Post Office, Oval': 0.0011915052556235653,
 "Newgate Street , St. Paul's": 0.0022868262548216313,
 'Hyde Park Corner, Hyde Park': 0.004928581383821547,
 'Walnut Tree Walk, Vauxhall': 0.00105124374019003,
 'Royal London Hospital, Whitechapel': 0.002835503861892071,
 'Lambeth Road, Vauxhall': 0.0009569927256476273,
 'Endsleigh Gardens, Euston': 0.00158734524645679,
 'Great Tower Street, Monument': 0.0026819639507621356,
 'Liverpool Road (N1 Centre), Angel': 0.0017237378047008003,
 'Borough Road, Elephant & Castle': 0.0010917973829493103,
 'Commercial Street, Shoreditch': 0.0009347870361819219,
 'Pindar Street, Liverpool Street': 0.0007168014372223221,
 'Old Quebec Street, Marylebone': 0.0016566449806357125,
 'Baker Street, Marylebone': 0.0014393885076274399,
 'Belgrave Road, Victoria': 0.0013445028193894248,
 'Triangle Car Park, Hyde Park': 0.002158407354550421,
 "Queen's Gate (Central), South Kensington": 0.0012637174528197447,
 'Warren Street Station, Euston': 0.0027808324644922893,
 'Moorfields, Moorgate': 0.0029407190465858706,
 'Kennington Cross, Kennington': 0.0017796074509401547,
 "Wright's Lane, Kensington": 0.0021088029817067123,
 'LSBU (Borough Road), Elephant & Castle': 0.000815118439426759,
 'Bayswater Road, Hyde Park': 0.0018904234163521997,
 'Northumberland Avenue, Strand': 0.0012842878081538148,
 'Lower Thames Street, Monument': 0.0009028683388060958,
 'Frampton Street, Paddington': 0.0009503791278500425,
 'Strand, Strand': 0.0019533855937897476,
 'Knightsbridge, Hyde Park': 0.00048137333524861137,
 'Leman Street, Aldgate': 0.001586156512353516,
 'Gloucester Street, Pimlico': 0.0012657097021960748,
 'Claremont Square, Angel': 0.0007037139417752055,
 'LMU Commercial Road, Whitechapel': 0.0012660839590758022,
 'Rampayne Street, Pimlico': 0.0013943702894754519,
 'Gloucester Road Station, South Kensington': 0.0021974791525523345,
 'North Wharf Road, Paddington': 0.0010324408110789491,
 'Wellington Arch, Hyde Park': 0.002367841303528594,
 'Palace Gate, Kensington Gardens': 0.001971017763219132,
 'Nutford Place, Marylebone': 0.0008095238215024723,
 "Trebovir Road, Earl's Court": 0.0011787046688958608,
 'Pont Street, Knightsbridge': 0.0013010633060652787,
 "Emperor's Gate, South Kensington": 0.0013729831387427566,
 'Lambeth North Station, Waterloo': 0.0010885216177778999,
 'Hampton Street, Walworth': 0.0013367379763596567,
 'Chepstow Villas, Notting Hill': 0.001009511080246175,
 'Lexham Gardens, Kensington': 0.0012218841969546602,
 'Ashley Place, Victoria': 0.0013397264453700094,
 'Southampton Place, Holborn': 0.001232448267655577,
 'Sumner Place, South Kensington': 0.0010376856924160704,
 'North Audley Street, Mayfair': 0.001425862556321315,
 'Risinghill Street, Angel': 0.000547375493678435,
 'Westbourne Green, Westbourne': 0.0007551164802283041,
 'Sun Street, Liverpool Street': 0.0015394240012637525,
 'Graham Street, Angel': 0.0012868618623590213,
 'Albert Gate, Hyde Park': 0.0035284019772274227,
 'Baylis Road, Waterloo': 0.0025958608800515574,
 'Warwick Road, Olympia': 0.0014662676238222103,
 'Claverton Street, Pimlico': 0.0009940925289873808,
 "London Zoo,  The Regent's Park": 0.0007287385708632868,
 'Harper Road, The Borough': 0.0008690674686334205,
 'Elizabeth Bridge, Victoria': 0.0016610717106344838,
 'Carey Street, Holborn': 0.0008996010852820664,
 'Grosvenor Road, Pimlico': 0.0007265818094880742,
 'Kingsway, Covent Garden': 0.0006147579863001816,
 'Tooley Street, Bermondsey': 0.003337824683591198,
 'Kensington Church Street, Kensington': 0.0013156277753190778,
 'Poured Lines, Bankside': 0.0009208607637923357,
 'Bucknall Street, Covent Garden': 0.0009471043594386555,
 'Tysoe Street, Clerkenwell': 0.0013676938399724723,
 'Clifton Road, Maida Vale': 0.001111485280231616,
 'Queen Mother Sports Centre, Victoria': 0.0014920434002079412,
 'Queensway, Kensington Gardens': 0.0017369535368356836,
 'Whitehall Place, Strand': 0.0026282278766310545,
 'Marylebone Lane, Marylebone': 0.0014520175677028276,
 'Pall Mall East, West End': 0.0017663156728260888,
 'Kennington Road, Vauxhall': 0.0011306528610369347,
 'Regency Street, Westminster': 0.0012468340113271931,
 'Bedford Way, Bloomsbury': 0.0009793231508981907,
 'Black Lion Gate, Kensington Gardens': 0.003313061338962502,
 "St. Martin's Street, West End": 0.0010396707462974962,
 'Berry Street, Clerkenwell': 0.0014144593859190526,
 'Craven Street, Strand': 0.0026405324021258917,
 'Brushfield Street, Liverpool Street': 0.004143081568488996,
 'Dorset Square, Marylebone': 0.0017021166223267052,
 'Wardour Street, Soho': 0.0019249714411659392,
 'Portland Place, Marylebone': 0.0012782518400050518,
 'Riverlight North, Nine Elms': 0.0015989797087306774,
 'Bell Street , Marylebone': 0.0012329892456002785,
 'South Wharf Road, Paddington': 0.001238883156911103,
 'Grosvenor Crescent, Belgravia': 0.0006329328432751837,
 'Horseferry Road, Westminster': 0.0015147584205187803,
 'New Road 1 , Whitechapel': 0.0018420089386191787,
 "Queen's Gate (South), South Kensington": 0.0013110475861082135,
 'Gloucester Terrace, Bayswater': 0.0008898280682778277,
 'Alderney Street, Pimlico': 0.0015158254517369833,
 'Mallory Street, Marylebone': 0.0006258289765875064,
 'Waterloo Road, South Bank': 0.0009905333732823452,
 'Seville Street, Knightsbridge': 0.001392564890192863,
 'Bourne Street, Belgravia': 0.0010995436508177642,
 'Notting Hill Gate Station, Notting Hill': 0.0017477538236814467,
 'St. Mary Axe, Aldgate': 0.0012695322245162026,
 'Belvedere Road 1, South Bank': 0.001536935333920081,
 "London Zoo Car Park, The Regent's Park": 0.0007437952277286309,
 'Long Lane , Bermondsey': 0.001121016266181965,
 'Kennington Lane Rail Bridge, Vauxhall': 0.001967492362820836,
 'Barbican Centre, Barbican': 0.0012677323846489246,
 'Embankment (Savoy), Strand': 0.0010800969197556274,
 'Kensington Gore, Knightsbridge': 0.0009118132271432597,
 'Westminster University, Marylebone': 0.0008749855068134519,
 "St. George's Square, Pimlico": 0.001342970368757314,
 'Vincent Square, Westminster': 0.0007143282165928602,
 'Sackville Street, Mayfair': 0.00159715484090257,
 "The Tennis Courts, The Regent's Park": 0.0010422068443856091,
 'Ontario Street, Elephant & Castle': 0.0012833012452267865,
 'Bank of England Museum, Bank': 0.0014165835417073588,
 'Wellington Street , Strand': 0.0020684842659662883,
 'Eastbourne Mews, Paddington': 0.0018680432241222605,
 "Queen's Gate (North), Kensington": 0.001431031965831859,
 'Black Prince Road, Vauxhall': 0.0011856663786476505,
 'Montpelier Street, Knightsbridge': 0.0015871979073550234,
 'Tavistock Street, Covent Garden': 0.001652884225948392,
 'Dickens Square, Borough': 0.0008181295108314554,
 'Empire Square, The Borough': 0.0015016753689069957,
 "Nevern Place, Earl's Court": 0.0007679729139020571,
 'Bunhill Row, Moorgate': 0.0018453112952907895,
 'Concert Hall Approach, South Bank': 0.00035046937784312144,
 'Curlew Street, Shad Thames': 0.0018398547561518412,
 'Kensington Olympia Station, Olympia': 0.0009521134458509361,
 'Swan Street, The Borough': 0.001086024120013951,
 'Serpentine Car Park, Hyde Park': 0.0025294331321875627,
 'Flood Street, Chelsea': 0.002174596897638339,
 'Lower Marsh, Waterloo': 0.001187382940246434,
 'Imperial College, Knightsbridge': 0.0026966085086595395,
 'St. George Street, Mayfair': 0.0013606259180817325,
 'Goswell Road (City Uni), Finsbury': 0.0007683104033799502,
 'Vauxhall Street, Vauxhall': 0.00132541288145819,
 'George Street, Marylebone': 0.0013739341743413064,
 'Macclesfield Rd, St Lukes': 0.0012573454642762823,
 'Devonshire Terrace, Bayswater': 0.0014363756003193142,
 'Southampton Street, Strand': 0.0015009473386313119,
 'High Holborn , Covent Garden': 0.001686434377293531,
 'Millennium Hotel, Mayfair': 0.0008373353624314831,
 "Queen's Gate, Kensington Gardens": 0.0019385157659200193,
 'Cloudesley Road, Angel': 0.0007401617955412074,
 'Wormwood Street, Liverpool Street': 0.003991879749847398,
 'Pembridge Villas, Notting Hill': 0.00090046411370637,
 'Palace Gardens Terrace, Notting Hill': 0.0014111375569993364,
 "Prince Albert Road, The Regent's Park": 0.0010769150179053733,
 'Bermondsey Street, Bermondsey': 0.0017274905249393614,
 'King Edward Walk, Waterloo': 0.0004831472952564679,
 'Waterloo Bridge, South Bank': 0.0007446236348805804,
 'Sardinia Street, Holborn': 0.0011419078471196355,
 'Frith Street, Soho': 0.0015138961989754763,
 'Butler Place, Westminster': 0.0010680962259231302,
 "Lord's, St. John's Wood": 0.0004264079345568141,
 'Howick Place, Westminster': 0.0018855326441165597,
 'Tower Wharf, Bermondsey': 0.0014751262974635536,
 'Charlotte Street, Fitzrovia': 0.0010419440671844116,
 'Paddington Green, Paddington': 0.0004957526136419247,
 'Natural History Museum, South Kensington': 0.0017254054725375472,
 'Farm Street, Mayfair': 0.000786071945820544,
 'George Row, Bermondsey': 0.0014905199405818906,
 'Harrowby Street, Marylebone': 0.001081341698058992,
 'Turquoise Island, Notting Hill': 0.00114924768943081,
 'Millbank Tower, Pimlico': 0.001127694803755854,
 'South Kensington Station, South Kensington': 0.0021231472098030015,
 'Royal College Street, Camden Town': 0.0009842578956787609,
 'Brick Lane Market, Shoreditch': 0.0011469036085504651,
 'Clifford Street, Mayfair': 0.001065001921212752,
 'City Road, Angel': 0.0009440685288374009,
 'Howland Street, Fitzrovia': 0.0017047116174409094,
 'Waterloo Station 2, Waterloo': 0.0017491668605297303,
 'Clapham Common Station, Clapham Common': 0.00208196605086863,
 'Cadogan Gardens, Chelsea': 0.0015945473490056293,
 'Waterloo Station 1, Waterloo': 0.00440818613135151,
 "Aberdeen Place, St. John's Wood": 0.0007882189884545097,
 'Snow Hill, Farringdon': 0.001023844517595452,
 'Columbia Road, Shoreditch': 0.001354766500221604,
 'Fire Brigade Pier, Vauxhall': 0.0009280108633447565,
 'Sedding Street, Sloane Square': 0.0019042104594972566,
 'Red Lion Square, Holborn': 0.0008229142006797223,
 'Maida Vale, Maida Vale': 0.0015242522057658974,
 'Broadcasting House, Marylebone': 0.0013501995184646404,
 'Northington Street , Holborn': 0.0014032309405475221,
 'Lansdowne Drive, Hackney Central': 0.001045109476910553,
 'Fanshaw Street, Hoxton': 0.0013764859686369807,
 "Pancras Road, King's Cross": 0.0008000831368903409,
 'Abbey Orchard Street, Westminster': 0.0012582016950366337,
 'Central House, Aldgate': 0.0016071072572882304,
 'Grafton Street, Mayfair': 0.0008930978608324171,
 'Farringdon Lane, Clerkenwell': 0.001018863107591795,
 'Sadlers Sports Centre, Finsbury': 0.0011874076401711927,
 'Sancroft Street, Vauxhall': 0.0007540888791342348,
 'Gloucester Road (Central), South Kensington': 0.0009126324532469357,
 'Derry Street, Kensington': 0.002445217410253378,
 'Curzon Street, Mayfair': 0.0011295964355478845,
 'Tavistock Place, Bloomsbury': 0.0010738195014556638,
 'Royal Avenue 1, Chelsea': 0.0007548811094376477,
 'Vicarage Gate, Kensington': 0.0007119672036468162,
 "Penywern Road, Earl's Court": 0.0013647408665269046,
 'Shoreditch High Street, Shoreditch': 0.0019820370246549,
 'Gloucester Road (North), Kensington': 0.0014014714472601584,
 'Webber Street , Southwark': 0.001343853309474584,
 'Breams Buildings, Holborn': 0.0010558486649831062,
 'Great Titchfield Street, Fitzrovia': 0.0011051994648924488,
 'Golden Square, Soho': 0.0016910940700215768,
 'Panton Street, West End': 0.0019621943116603204,
 'Arundel Street, Temple': 0.0009570045133893972,
 'Portugal Street, Holborn': 0.000920825538426308,
 'Rochester Row, Westminster': 0.0010453731250081896,
 "Waterloo Place, St. James's": 0.0012896397510206532,
 'Warwick Square, Pimlico': 0.0011196072193901084,
 'Sloane Avenue, Knightsbridge': 0.0013508199001554047,
 'Royal Avenue 2, Chelsea': 0.0011008123004884796,
 'Argyll Road, Kensington': 0.0008758805085092006,
 'Green Street, Mayfair': 0.0016301203531066503,
 'Eccleston Place, Victoria': 0.0021503520039789946,
 'Dock Street, Wapping': 0.0014836677029148307,
 'Margery Street, Clerkenwell': 0.0008978616907103626,
 'Cadogan Place, Knightsbridge': 0.001019609648589408,
 'Great Percy Street, Clerkenwell': 0.0008959700747136858,
 'Chadwell Street, Angel': 0.0007359448360025837,
 'Colombo Street, Southwark': 0.00047193680313756893,
 'Belgrave Square, Belgravia': 0.0008399104488368634,
 'Hinde Street, Marylebone': 0.0017610939962811167,
 'Porchester Place, Paddington': 0.0015560465212728016,
 'Guildhouse Street, Victoria': 0.000914822038212783,
 'Old Brompton Road, South Kensington': 0.0012655286039401322,
 'Smith Square, Westminster': 0.0014291471197200652,
 'Rodney Road , Walworth': 0.000911703411553085,
 'Beaumont Street, Marylebone': 0.0013130241504419665,
 'Fashion Street, Whitechapel': 0.0009559778193945624,
 'Houghton Street, Strand': 0.0009988314171485726,
 'Tyers Gate, Bermondsey': 0.0010750766962735428,
 'Charles II Street, West End': 0.0012905868110066612,
 'Broadwick Street, Soho': 0.0017752092685795926,
 'Southwick Street, Paddington': 0.0011602039352099182,
 'Princes Square, Bayswater': 0.0006992880556794326,
 'South Audley Street, Mayfair': 0.0007903478251404163,
 'Foley Street, Fitzrovia': 0.0013862063158496458,
 'Wells Street, Fitzrovia': 0.0017568635274655424,
 "St Mary's Hospital, Paddington": 0.001594848786531684,
 'Rathbone Street, Fitzrovia': 0.0009191085674436852,
 'Geraldine Street, Elephant & Castle': 0.0006196244879425215,
 "Baldwin Street, St. Luke's": 0.0013311602557878786,
 'Clifton Street, Shoreditch': 0.000762054086862231,
 'Palissy Street, Shoreditch': 0.0009965013607929289,
 'Moor Street, Soho': 0.002238317791877652,
 'Stanhope Gate, Mayfair': 0.000736723488075994,
 'Store Street, Bloomsbury': 0.001380461802613681,
 'Greycoat Street , Westminster': 0.0006287534750753529,
 'Strata, Elephant & Castle': 0.002319651032481386,
 'Grosvenor Square, Mayfair': 0.0014105506775863243,
 'Cleaver Street, Kennington': 0.0007415031564026928,
 'Rotherhithe Roundabout, Rotherhithe': 0.001024868080796996,
 'George Place Mews, Marylebone': 0.0009528247525383302,
 'Holland Park, Kensington': 0.0006064484061078126,
 'Kensington Town Hall, Kensington': 0.0006075048673745928,
 'Exhibition Road Museums 1, South Kensington': 0.0012939552903773904,
 'Ebury Bridge, Pimlico': 0.0010561631681135152,